allow-lan: true
bind-address: '*'
dns:
    default-nameserver:
        - 223.5.5.5
        - 223.6.6.6
    enable: true
    ipv6: false
    nameserver:
        - 223.5.5.5
        - 223.6.6.6
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
